In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('income.csv')
x = df[['age', 'income']].to_numpy()

def kmeans(x, k=2, max_iters=100):
    np.random.seed(42)
    indexes = np.random.choice(len(x), k, replace=False)
    centroids = x[indexes] 

    for i in range(max_iters):
        distances = np.sqrt(((x[:, np.newaxis] - centroids)**2).sum(axis=2)) 
        print(distances)
        labels = np.argmin(distances, axis=1)

        old = centroids.copy()
        for j in range(k):
            if len(x[labels == j]) > 0:
                centroids[j] = x[labels == j].mean(axis=0)
        if np.all(old == centroids):
            break

    return labels, centroids

k = 2
labels, centroids = kmeans(x, k)


[[     0.          19000.00002632]
 [ 20000.0001      39000.00001282]
 [  9000.00022222  10000.00005   ]
 [ 10000.00005      9000.        ]
 [ 80000.00140625  99000.0009899 ]
 [ 85000.00084706 104000.00058173]
 [ 90000.00108889 109000.00077523]
 [ 92000.00065761 111000.00045045]
 [ 86000.00047093 105000.00030476]
 [ 60000.00053333  79000.00031013]
 [ 67000.00074627  86000.00047093]
 [ 25000.00002      6000.00033333]
 [ 22000.           3000.00016667]
 [ 19000.00002632      0.        ]
 [ 20500.00009756   1500.00033333]
 [ 17000.00073529   2000.004     ]
 [  5000.01689997  14000.00514286]
 [  7000.01399999  12000.00704166]
 [  6000.0213333   13000.00865384]
 [ 10000.0072      29000.00208621]
 [ 12000.00816666  31000.00272581]
 [ 12000.006        7000.00864285]]
[[ 38333.00130436  17929.00011155]
 [ 18333.00174549  37929.        ]
 [ 47333.00067606   8929.        ]
 [ 48333.00083794   7929.00006306]
 [ 41667.0003      97929.00086287]
 [ 46667.00004286 102929.00048577]
 [ 51667.00015484 1

In [23]:
print(labels)

[1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]


In [24]:
print(centroids)

[[    38 150000]
 [    33  62633]]
